
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud Formation to build Continuos Integration and deployment stack for Circle CI

Parameters:
  AWSAccountId:
    Description: AWSAccountId
    Type: String
  CodeDeployApplicationName:
    Description: CodeDeployApplicationName
    Type: String
  AWSRegion:
    Description: CodeDeployApplicationName
    Type: String
  S3BucketNameCD:
    Description: S3BucketNameCD
    Type: String
  LambdaBucketNameCD:
    Description: S3BucketNameCD
    Type: String
Resources:
  CircleCIUser:
    Type: AWS::IAM::User
    Properties:
      UserName: circleci
      Path: "/"
      Policies:
      - PolicyName: CircleCIUploadToS3
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            Action: 
              - "s3:PutObject"
              - "s3:GetObject"
            Effect: Allow
            Resource: [!Join ["",["arn:aws:s3:::",!Ref S3BucketNameCD,"/*"]],!Join ["",["arn:aws:s3:::",!Ref LambdaBucketNameCD,"/*"]]]
      - PolicyName: CircleCILambda
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            Action: 
              - "lambda:*"
            Effect: Allow
            Resource : "*"
      - PolicyName: CirlceCICodeDeploy
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Action: 
                - "codedeploy:RegisterApplicationRevision"
                - "codedeploy:GetApplicationRevision"
              Resource: 
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":application:",!Ref CodeDeployApplicationName]]
            - Effect: Allow
              Action: 
                - "codedeploy:CreateDeployment"
                - "codedeploy:GetDeployment"
              Resource: "*"
            - Effect: Allow
              Action: 
                - "codedeploy:GetDeploymentConfig"
              Resource: 
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":deploymentconfig:CodeDeployDefault.OneAtATime"]]
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":deploymentconfig:CodeDeployDefault.HalfAtATime"]]
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":deploymentconfig:CodeDeployDefault.AllAtOnce"]]
      - PolicyName: circleci-ec2-ami
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            Action: 
              - "ec2:AttachVolume"
              - "ec2:AuthorizeSecurityGroupIngress"
              - "ec2:CopyImage"
              - "ec2:CreateImage"
              - "ec2:CreateKeypair"
              - "ec2:CreateSecurityGroup"
              - "ec2:CreateSnapshot"
              - "ec2:CreateTags"
              - "ec2:CreateVolume"
              - "ec2:DeleteKeyPair"
              - "ec2:DeleteSecurityGroup"
              - "ec2:DeleteSnapshot"
              - "ec2:DeleteVolume"
              - "ec2:DeregisterImage"
              - "ec2:DescribeImageAttribute"
              - "ec2:DescribeImages"
              - "ec2:DescribeInstances"
              - "ec2:DescribeInstanceStatus"
              - "ec2:DescribeRegions"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSnapshots"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeTags"
              - "ec2:DescribeVolumes"
              - "ec2:DetachVolume"
              - "ec2:GetPasswordData"
              - "ec2:ModifyImageAttribute"
              - "ec2:ModifyInstanceAttribute"
              - "ec2:ModifySnapshotAttribute"
              - "ec2:RegisterImage"
              - "ec2:RunInstances"
              - "ec2:StopInstances"
              - "ec2:TerminateInstances"
            Effect: Allow
            Resource: "*"