version: 0.0

os: linux
files:
  - source: /
    destination: /home/centos/webapp
hooks:
  BeforeInstall:
    - location: cd_scripts/clean_server.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: cd_scripts/install_os_dependencies.sh
      timeout: 600
      runas: root
    - location: cd_scripts/install_python_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: cd_scripts/start_server.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: cd_scripts/stop_server.sh
      timeout: 600
      runas: root